#!/bin/sh
if [ $HOSTNAME = "S2" ] ; then
	echo "Frodo"
	module purge
	module load intel
	export MPI_ROOT=/usr/local/openmpi/1.6/intel12
	export MPI_INCLUDE=$MPI_ROOT/include
	export MPI_LIB=$MPI_ROOT/lib
	export MPI_LIB_FILE=$MPI_LIB/libmpi.so
	export OPENCL_ROOT=/opt/intel/opencl-1.2-3.0.67279/
	export ARMADILLO_ROOT=$HOME/local 
	export CL_KERNELS=/mnt/global/LCSE/gerlebacher/src/rbf_fd/rbffd_gpu/src/cl_kernels
	echo "Frodo"
elif [ $HOSTNAME = "hpc-15-35" ] ; then 
	echo "fsu mic"
	module purge
	module load intel
    module load intel-impi-x86_64
	export MPI_ROOT=$I_MPI_ROOT/
	export MPI_INCLUDE=$MPI_ROOT/include64
	export MPI_LIB=$MPI_ROOT/lib64
	export MPI_LIB_FILE=$MPI_LIB/libmpich.so
	export OPENCL_ROOT=/opt/intel/opencl-1.2-3.0.67279/
	export ARMADILLO_ROOT=$HOME/local/usr
	export CL_KERNELS=$HOME/src/rbffd_gpu/src/cl_kernels
	export BOOST_ROOT=/panfs/storage.local/scs/home/gerlebacher/local/boost_1_53_0/
	export BOOST_INCLUDEDIR=/panfs/storage.local/scs/home/gerlebacher/local/boost_1_53_0/
	echo "fsu mic"
elif [ $HOSTNAME = "casiornis" ] ; then
	echo "casiorni"
	module purge
	module load intel
	export MPI_ROOT=/usr/mpi/intel/mvapich2-1.6-qlc/
	export MPI_INCLUDE=$MPI_ROOT/include
	export MPI_LIB=$MPI_ROOT/lib
	export MPI_LIB_FILE=$MPI_LIB/libmpich.so
	export OPENCL_ROOT=/opt/intel/opencl-1.2-3.0.67279/
	export ARMADILLO_ROOT=$HOME/local/usr
	export CL_KERNELS=$HOME/src/rbffd_gpu/src/cl_kernels
	export BOOST_ROOT=/usr/include/boost
	#export BOOST_INCLUDEDIR=/usr/include
	#export BOOST_LIBDIR=/usr/lib64
	export BOOST_ROOT=$HOME/local/boost_1_53_0/
	export BOOST_INCLUDEDIR=$BOOST_ROOT
	export FFTW_ROOT=/panfs/storage.local/scs/home/gerlebacher/local/usr
	echo "casiorni"
fi


