#!/bin/bash -l 
#PBS -l walltime=00:05:00,nodes=1:ppn=8
#PBS -q batch
#PBS -m ae 
#PBS -N example2_simple
## PBS -e error.$PBS_JOBID
## PBS -o output.$PBS_JOBID


echo ------------------------------------------------------
echo -n 'Job is running on node '; cat $PBS_NODEFILE
echo ------------------------------------------------------
echo PBS: qsub is running on $PBS_O_HOST
echo PBS: originating queue is $PBS_O_QUEUE
echo PBS: executing queue is $PBS_QUEUE
echo PBS: working directory is $PBS_O_WORKDIR
echo PBS: execution mode is $PBS_ENVIRONMENT
echo PBS: job identifier is $PBS_JOBID
echo PBS: job name is $PBS_JOBNAME
echo PBS: node file is $PBS_NODEFILE
echo PBS: current home directory is $PBS_O_HOME
echo PBS: PATH = $PBS_O_PATH
echo ------------------------------------------------------

#env |grep PBS

#source $HOME/../shared/cascade_env.sh
echo "Loading intel module" 
module load intel/2013
module load impi/intel
module load mkl/11.0.4.183
module load cmake
module load fftw
module load boost
module load vtk/5.4.2
module load metis

export ARMADILLO_ROOT=$HOME/../shared/intel-soft

module list

#echo "============================"
#env
#echo "============================"

export LD_LIBRARY_PATH=/opt/intel/opencl/lib64:$LD_LIBRARY_PATH

date

MD=165
N=27556
STEN_SIZE=17

NEW_WORKDIR=$PBS_O_WORKDIR/test_${N}_${PBS_NP}proc

mkdir -p $NEW_WORKDIR
cd $NEW_WORKDIR

# Read grid, generate stencils (Note: -c 4 is required because MD nodes have 4 cols)
$PBS_O_WORKDIR/sten_gen.x -g ~/sphere_grids/md${MD}.${N} -c 4 -N ${N} -n ${STEN_SIZE} -w 0 -l 100

echo "sten_gen Exit status: $?"

# Decompose domain for parallel run into PBS_NP partitions
gpmetis metis_stencils.graph ${PBS_NP}

echo "gpmetis Exit status: $?"

mpirun -l -np ${PBS_NP} $PBS_O_WORKDIR/compute_weights.x -w 15 -g input_grid.ascii -a -N ${N} -n ${STEN_SIZE} --eps_c1 0.035 --eps_c2 0.1 -p metis_stencils.graph.part.${PBS_NP}

echo "compute_weights Exit status: $?"

mpirun -l -np ${PBS_NP} $PBS_O_WORKDIR/evaluate_derivatives.x -g input_grid.ascii -a -N ${N}  -n ${STEN_SIZE} --eps_c1=0.035 --eps_c2=0.1 -w 15 

echo "evaluate_derivatives Exit status: $?"

date
